bev_node:
  ros__parameters:
    model_path: "/home/hesam/Desktop/depth_node/model/unidepth/unidepthv2_vits14_simp.onnx"
    output_width: 1241
    output_height: 376
    intrinsic_image_width: 1241
    intrinsic_image_height: 376
    multiplication_ratio: 125
    starting_x: -1500
    starting_y: 1000
    camera_intrinsics:
      K: [721.5377, 0.0, 609.5593, 0.0, 721.5377, 172.854, 0.0, 0.0, 1.0]
      dist: [-0.171, 0.189, 0.000, 0.000, 0.000]

ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.1
    two_d_mode: true
    publish_tf: true

    map_frame: "world"
    odom_frame: "odom"
    base_link_frame: "base_link"
    world_frame: "world"

    imu0: "/kitti/oxts/imu"
    imu0_config: [false, false, false, 
                true, true, true,
                false, false, false,
                true, true, true, 
                true, true, true] 
    imu0_differential: false
    imu0_queue_size: 10
    imu0_remove_gravitational_acceleration: true

    odom0: "/odometry/gps"
    odom0_config: [true, true, true,
                false, false, true,
                false, false, false,
                false, false, false,
                false, false, false]
    odom0_differential: false
    odom0_queue_size: 10
    process_noise_covariance: [
      1.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  1.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  10.0, 0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.03, 0.0,  0.0,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.03, 0.0,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.1,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.25,  0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.25,  0.0,   0.0,  0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.04,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.01, 0.0,  0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,  0.01, 0.0,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,  0.0,  0.5,  0.0,  0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.01, 0.0,   0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.01,  0.0,
      0.0,  0.0,  0.0,  0.0,  0.0,  0.0,  0.0,   0.0,   0.0,   0.0,  0.0,  0.0,  0.0,  0.0,   0.015
    ]
